/// Product dimension: one row per product sold by Adventure Works, including its category hierarchy and standard cost.
table 'Product'

	/// Number of distinct products in the filter context. DISTINCTCOUNT of Product Key.
	measure 'Product Count' = DISTINCTCOUNT('Product'[Product Key])
		formatString: #,##0
		displayFolder: Counts

	/// Surrogate key for the product dimension. Foreign key in the Sales fact table.
	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: product_key

	/// Product name.
	column 'Product'
		dataType: string
		summarizeBy: none
		sourceColumn: product

	/// List price cost basis of the product.
	column 'Standard Cost'
		dataType: double
		summarizeBy: none
		sourceColumn: standard_cost

	/// Product color.
	column 'Color'
		dataType: string
		summarizeBy: none
		sourceColumn: color

	/// Product subcategory (mid level of the product hierarchy).
	column 'Subcategory'
		dataType: string
		summarizeBy: none
		sourceColumn: subcategory

	/// Product category (top level of the product hierarchy).
	column 'Category'
		dataType: string
		summarizeBy: none
		sourceColumn: category

	/// Hex color code for visual background formatting (used in product KPI tiles and conditional formatting). Hidden; not for end users.
	column 'Background Color Format'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: background_color_format

	/// Hex color code for visual font formatting (used in product KPI tiles and conditional formatting). Hidden; not for end users.
	column 'Font Color Format'
		dataType: string
		isHidden
		summarizeBy: none
		sourceColumn: font_color_format

	hierarchy 'Product Hierarchy'

		level 'Category'
			column: 'Category'

		level 'Subcategory'
			column: 'Subcategory'

		level 'Product'
			column: 'Product'

	partition 'Product' = entity
		mode: directLake
		source
			entityName: dim_product
			expressionSource: 'DirectLake - aw_gold'
