/// Sales territory / region dimension: one row per sales territory, grouped into country and geographic group.
table 'Region'

	/// Number of distinct sales territories in the filter context. DISTINCTCOUNT of Sales Territory Key.
	measure 'Region Count' = DISTINCTCOUNT('Region'[Sales Territory Key])
		formatString: #,##0
		displayFolder: Counts

	/// Surrogate key for the region dimension. Foreign key in the Sales fact table and Salesperson Region bridge table.
	column 'Sales Territory Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: salesterritory_key

	/// Sales territory region name.
	column 'Region'
		dataType: string
		summarizeBy: none
		sourceColumn: region

	/// Country of the sales territory.
	column 'Country'
		dataType: string
		summarizeBy: none
		sourceColumn: country
		dataCategory: Country

	/// Geographic group of the sales territory (e.g. North America, Europe, Pacific).
	column 'Group'
		dataType: string
		summarizeBy: none
		sourceColumn: group

	hierarchy 'Region Geography'

		level 'Group'
			column: 'Group'

		level 'Country'
			column: 'Country'

		level 'Region'
			column: 'Region'

	partition 'Region' = entity
		mode: directLake
		source
			entityName: dim_region
			schemaName: dbo
			expressionSource: 'DirectLake - aw_gold'
