/// Reseller dimension: one row per reseller (distributor) that purchases Adventure Works products, including its geography.
table 'Reseller'

	/// Number of distinct resellers in the filter context. DISTINCTCOUNT of Reseller Key.
	measure 'Reseller Count' = DISTINCTCOUNT('Reseller'[Reseller Key])
		formatString: #,##0
		displayFolder: Counts

	/// Surrogate key for the reseller dimension. Foreign key in the Sales fact table.
	column 'Reseller Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: reseller_key

	/// Reseller business type (e.g. Warehouse, Value Added Reseller, Specialty Bike Shop).
	column 'Business Type'
		dataType: string
		summarizeBy: none
		sourceColumn: business_type

	/// Reseller name.
	column 'Reseller'
		dataType: string
		summarizeBy: none
		sourceColumn: reseller

	/// City where the reseller is located.
	column 'City'
		dataType: string
		summarizeBy: none
		sourceColumn: city
		dataCategory: City

	/// State or province where the reseller is located.
	column 'State Province'
		dataType: string
		summarizeBy: none
		sourceColumn: state_province
		dataCategory: StateOrProvince

	/// Country or region where the reseller is located.
	column 'Country Region'
		dataType: string
		summarizeBy: none
		sourceColumn: country_region
		dataCategory: Country

	hierarchy 'Reseller Geography'

		level 'Country Region'
			column: 'Country Region'

		level 'State Province'
			column: 'State Province'

		level 'City'
			column: 'City'

	partition 'Reseller' = entity
		mode: directLake
		source
			entityName: dim_reseller
			schemaName: dbo
			expressionSource: 'DirectLake - aw_gold'
