/// Sales fact: one row per reseller sales order line, with deriveded profit. Grain = sales order line.
table 'Sales'

	/// Total revenue from reseller sales in the filter context. SUM of the Sales Amount column.
	measure 'Total Sales' = SUM('Sales'[Sales Amount])
		formatString: \$#,##0.00;(\$#,##0.00)
		displayFolder: Sales

	/// Total cost of goods sold in the filter context. SUM of the Cost Amount column.
	measure 'Total Cost' = SUM('Sales'[Cost Amount])
		formatString: \$#,##0.00;(\$#,##0.00)
		displayFolder: Sales

	/// Total gross profit in the filter context. SUM of the pre-computed Profit Amount column (Sales Amount minus Cost Amount).
	measure 'Total Profit' = SUM('Sales'[Profit Amount])
		formatString: \$#,##0.00;(\$#,##0.00)
		displayFolder: Profitability

	/// Gross profit as a percentage of total revenue. DIVIDE(Total Profit, Total Sales); returns blank when sales is zero.
	measure 'Profit Margin %' = DIVIDE([Total Profit], [Total Sales])
		formatString: 0.00%
		displayFolder: Profitability

	/// Total units sold in the filter context. SUM of the Quantity column across all order lines.
	measure 'Total Quantity' = SUM('Sales'[Quantity])
		formatString: #,##0
		displayFolder: Sales

	/// Number of distinct sales orders in the filter context. DISTINCTCOUNT of Sales Order Number.
	measure 'Order Count' = DISTINCTCOUNT('Sales'[Sales Order Number])
		formatString: #,##0
		displayFolder: Counts

	/// Sales order number (degenerate dimension).
	column 'Sales Order Number'
		dataType: string
		summarizeBy: none
		sourceColumn: sales_order_number

	/// Date the sales order was placed. Foreign key linking to the Date dimension.
	column 'Order Date'
		dataType: dateTime
		isHidden
		formatString: General Date
		summarizeBy: none
		sourceColumn: order_date

	/// Foreign key linking to the Product dimension.
	column 'Product Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: product_key

	/// Foreign key linking to the Reseller dimension.
	column 'Reseller Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: reseller_key

	/// Foreign key linking to the Salesperson dimension.
	column 'Employee Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: employee_key

	/// Foreign key linking to the Region dimension.
	column 'Sales Territory Key'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: salesterritory_key

	/// Number of product units sold on this order line.
	column 'Quantity'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: sum
		sourceColumn: quantity

	/// List price per unit at the time of sale.
	column 'Unit Price'
		dataType: double
		isHidden
		summarizeBy: sum
		sourceColumn: unit_price

	/// Total revenue for this order line (unit price × quantity, after adjustments). Source for Total Sales.
	column 'Sales Amount'
		dataType: double
		isHidden
		summarizeBy: sum
		sourceColumn: sales

	/// Total cost of goods sold for this order line. Source for Total Cost.
	column 'Cost Amount'
		dataType: double
		isHidden
		summarizeBy: sum
		sourceColumn: cost

	/// Gross profit for this order line (Sales Amount minus Cost Amount), pre-computed in the Gold layer. Source for Total Profit.
	column 'Profit Amount'
		dataType: double
		isHidden
		summarizeBy: sum
		sourceColumn: profit

	partition 'Sales' = entity
		mode: directLake
		source
			entityName: fact_sales
			expressionSource: 'DirectLake - aw_gold'
