/// Targets fact: one row per salesperson per month with the assigned sales target. Grain = salesperson + month.
table 'Targets'

	/// Total assigned sales target in the filter context. SUM of the monthly Target amount across all salesperson-month combinations.
	measure 'Total Target' = SUM('Targets'[Target])
		formatString: \$#,##0.00;(\$#,##0.00)
		displayFolder: Targets

	/// Natural (HR) employee ID. Links to the Salesperson dimension via Employee ID.
	column 'Employee ID'
		dataType: int64
		isHidden
		formatString: 0
		summarizeBy: none
		sourceColumn: employee_id

	/// First day of the month for which the target is set. Foreign key linking to the Date dimension.
	column 'Target Month'
		dataType: dateTime
		isHidden
		formatString: General Date
		summarizeBy: none
		sourceColumn: target_month

	/// Monthly revenue target assigned to the salesperson (in dollars). Source for Total Target.
	column 'Target'
		dataType: double
		isHidden
		summarizeBy: sum
		sourceColumn: target

	partition 'Targets' = entity
		mode: directLake
		source
			entityName: fact_targets
			schemaName: dbo
			expressionSource: 'DirectLake - aw_gold'
